"""adiciona revision ao lancamento_item

Revision ID: 0b627cd33b88
Revises: 6147065c21c0
Create Date: 2026-07-29 14:37:59.805775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b627cd33b88'
down_revision: Union[str, None] = '6147065c21c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lancamento_item', sa.Column('revision', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lancamento_item', 'revision')
    # ### end Alembic commands ###
