"""inscricao adiciona ordem_apresentacao

Revision ID: 2b573a27850c
Revises: e37fd78112f0
Create Date: 2026-10-10 20:14:55.376792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b573a27850c'
down_revision: Union[str, None] = 'e37fd78112f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscricao', sa.Column('ordem_apresentacao', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inscricao', 'ordem_apresentacao')
    # ### end Alembic commands ###
