"""cria arena agendamento e pausa entre rodadas

Revision ID: 2e803240e889
Revises: a1c9f2e6b4d7
Create Date: 2026-08-04 23:23:02.218985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e803240e889'
down_revision: Union[str, None] = 'a1c9f2e6b4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arena',
    sa.Column('modalidade_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('niveis_aplicaveis', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['modalidade_id'], ['modalidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arena_modalidade_id'), 'arena', ['modalidade_id'], unique=False)
    op.create_table('agendamento',
    sa.Column('rodada_id', sa.UUID(), nullable=False),
    sa.Column('equipe_id', sa.UUID(), nullable=False),
    sa.Column('arena_id', sa.UUID(), nullable=False),
    sa.Column('ordem_na_arena', sa.Integer(), nullable=False),
    sa.Column('horario_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['arena_id'], ['arena.id'], ),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipe.id'], ),
    sa.ForeignKeyConstraint(['rodada_id'], ['rodada.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rodada_id', 'arena_id', 'ordem_na_arena', name='uq_agendamento_rodada_arena_ordem'),
    sa.UniqueConstraint('rodada_id', 'equipe_id', name='uq_agendamento_rodada_equipe')
    )
    op.create_index(op.f('ix_agendamento_arena_id'), 'agendamento', ['arena_id'], unique=False)
    op.create_index(op.f('ix_agendamento_equipe_id'), 'agendamento', ['equipe_id'], unique=False)
    op.create_index(op.f('ix_agendamento_rodada_id'), 'agendamento', ['rodada_id'], unique=False)
    op.add_column('modalidade', sa.Column('pausa_entre_rodadas_seg', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modalidade', 'pausa_entre_rodadas_seg')
    op.drop_index(op.f('ix_agendamento_rodada_id'), table_name='agendamento')
    op.drop_index(op.f('ix_agendamento_equipe_id'), table_name='agendamento')
    op.drop_index(op.f('ix_agendamento_arena_id'), table_name='agendamento')
    op.drop_table('agendamento')
    op.drop_index(op.f('ix_arena_modalidade_id'), table_name='arena')
    op.drop_table('arena')
    # ### end Alembic commands ###
