"""adiciona total ao lancamento

Revision ID: 6147065c21c0
Revises: 32c678f66da5
Create Date: 2026-07-29 14:30:22.885534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6147065c21c0'
down_revision: Union[str, None] = '32c678f66da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lancamento', sa.Column('total', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lancamento', 'total')
    # ### end Alembic commands ###
