"""partida adiciona nivel

Revision ID: 945b3f35bf48
Revises: b9cf38bbe748
Create Date: 2026-08-01 23:58:23.491596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945b3f35bf48'
down_revision: Union[str, None] = 'b9cf38bbe748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partida', sa.Column('nivel', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partida', 'nivel')
    # ### end Alembic commands ###
