"""cria hierarquia de evento, modalidade, ficha e tabelas antecipadas

Revision ID: de2bcad3385f
Revises: 267aeda7c480
Create Date: 2026-07-28 14:42:19.160555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de2bcad3385f'
down_revision: Union[str, None] = '267aeda7c480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipe',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evento',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'ATIVO', 'ENCERRADO', name='evento_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('entidade', sa.String(length=100), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('justificativa', sa.String(), nullable=True),
    sa.Column('antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('depois', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entidade_id'), 'audit_log', ['entidade_id'], unique=False)
    op.create_index(op.f('ix_audit_log_usuario_id'), 'audit_log', ['usuario_id'], unique=False)
    op.create_table('modalidade',
    sa.Column('evento_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('tipo_disputa', sa.Enum('INDIVIDUAL', 'CONFRONTO', name='tipo_disputa'), nullable=False),
    sa.Column('formato_chaveamento', sa.Enum('MATA_MATA', 'TODOS_CONTRA_TODOS', 'DUPLA_ELIMINACAO', name='formato_chaveamento'), nullable=True),
    sa.Column('niveis_aplicaveis', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('ficha_unica_entre_niveis', sa.Boolean(), nullable=False),
    sa.Column('qtd_rodadas', sa.Integer(), nullable=False),
    sa.Column('tentativas_por_rodada', sa.Integer(), nullable=False),
    sa.Column('duracao_maxima_rodada_seg', sa.Integer(), nullable=True),
    sa.Column('consolidacao', sa.Enum('SOMA_RODADAS', 'MELHOR_RODADA', 'MELHOR_N_RODADAS', name='consolidacao'), nullable=False),
    sa.Column('consolidacao_n', sa.Integer(), nullable=True),
    sa.Column('permite_total_negativo', sa.Boolean(), nullable=False),
    sa.Column('desempates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('RASCUNHO', 'PUBLICADA', 'ENCERRADA', name='modalidade_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modalidade_evento_id'), 'modalidade', ['evento_id'], unique=False)
    op.create_table('ficha',
    sa.Column('modalidade_id', sa.UUID(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'PUBLICADA', 'SUBSTITUIDA', name='ficha_status'), nullable=False),
    sa.Column('publicada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['modalidade_id'], ['modalidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modalidade_id', 'nivel', 'versao', name='uq_ficha_modalidade_nivel_versao')
    )
    op.create_index(op.f('ix_ficha_modalidade_id'), 'ficha', ['modalidade_id'], unique=False)
    op.create_table('inscricao',
    sa.Column('equipe_id', sa.UUID(), nullable=False),
    sa.Column('modalidade_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipe.id'], ),
    sa.ForeignKeyConstraint(['modalidade_id'], ['modalidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipe_id', 'modalidade_id', name='uq_inscricao_equipe_modalidade')
    )
    op.create_index(op.f('ix_inscricao_equipe_id'), 'inscricao', ['equipe_id'], unique=False)
    op.create_index(op.f('ix_inscricao_modalidade_id'), 'inscricao', ['modalidade_id'], unique=False)
    op.create_table('rodada',
    sa.Column('modalidade_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('modo_horario', sa.Enum('MANUAL', 'AUTOMATICO', name='modo_horario'), nullable=False),
    sa.Column('horario_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('AGENDADA', 'EM_ANDAMENTO', 'ENCERRADA', name='rodada_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['modalidade_id'], ['modalidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rodada_modalidade_id'), 'rodada', ['modalidade_id'], unique=False)
    op.create_table('grupo',
    sa.Column('ficha_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ficha_id'], ['ficha.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupo_ficha_id'), 'grupo', ['ficha_id'], unique=False)
    op.create_table('partida',
    sa.Column('rodada_id', sa.UUID(), nullable=False),
    sa.Column('equipe_a_id', sa.UUID(), nullable=False),
    sa.Column('equipe_b_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('AGENDADA', 'EM_ANDAMENTO', 'ENCERRADA', name='partida_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipe_a_id'], ['equipe.id'], ),
    sa.ForeignKeyConstraint(['equipe_b_id'], ['equipe.id'], ),
    sa.ForeignKeyConstraint(['rodada_id'], ['rodada.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partida_rodada_id'), 'partida', ['rodada_id'], unique=False)
    op.create_table('criterio',
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('tipo', sa.Enum('CONTADOR', 'BOOLEANO', 'ESCALA', 'PENALIDADE', 'MODIFICADOR', name='criterio_tipo'), nullable=False),
    sa.Column('pontos', sa.Numeric(), nullable=True),
    sa.Column('valores_permitidos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_ocorrencias', sa.Integer(), nullable=True),
    sa.Column('modificador_tipo', sa.Enum('PERCENTUAL', 'ZERA_TOTAL', name='modificador_tipo'), nullable=True),
    sa.Column('modificador_valor', sa.Numeric(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criterio_grupo_id'), 'criterio', ['grupo_id'], unique=False)
    op.create_table('lancamento',
    sa.Column('ficha_id', sa.UUID(), nullable=False),
    sa.Column('rodada_id', sa.UUID(), nullable=False),
    sa.Column('tentativa', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.UUID(), nullable=False),
    sa.Column('partida_id', sa.UUID(), nullable=True),
    sa.Column('arbitro_id', sa.UUID(), nullable=False),
    sa.Column('client_operation_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CONFIRMADO', 'ANULADO', name='lancamento_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['arbitro_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipe.id'], ),
    sa.ForeignKeyConstraint(['ficha_id'], ['ficha.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.id'], ),
    sa.ForeignKeyConstraint(['rodada_id'], ['rodada.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_operation_id', name='uq_lancamento_client_operation_id')
    )
    op.create_index(op.f('ix_lancamento_client_operation_id'), 'lancamento', ['client_operation_id'], unique=False)
    op.create_index(op.f('ix_lancamento_equipe_id'), 'lancamento', ['equipe_id'], unique=False)
    op.create_index(op.f('ix_lancamento_ficha_id'), 'lancamento', ['ficha_id'], unique=False)
    op.create_index(op.f('ix_lancamento_rodada_id'), 'lancamento', ['rodada_id'], unique=False)
    op.create_table('lancamento_item',
    sa.Column('lancamento_id', sa.UUID(), nullable=False),
    sa.Column('criterio_id', sa.UUID(), nullable=True),
    sa.Column('criterio_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ocorrencias', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(), nullable=True),
    sa.Column('pontos', sa.Numeric(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criterio_id'], ['criterio.id'], ),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lancamento_item_lancamento_id'), 'lancamento_item', ['lancamento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lancamento_item_lancamento_id'), table_name='lancamento_item')
    op.drop_table('lancamento_item')
    op.drop_index(op.f('ix_lancamento_rodada_id'), table_name='lancamento')
    op.drop_index(op.f('ix_lancamento_ficha_id'), table_name='lancamento')
    op.drop_index(op.f('ix_lancamento_equipe_id'), table_name='lancamento')
    op.drop_index(op.f('ix_lancamento_client_operation_id'), table_name='lancamento')
    op.drop_table('lancamento')
    op.drop_index(op.f('ix_criterio_grupo_id'), table_name='criterio')
    op.drop_table('criterio')
    op.drop_index(op.f('ix_partida_rodada_id'), table_name='partida')
    op.drop_table('partida')
    op.drop_index(op.f('ix_grupo_ficha_id'), table_name='grupo')
    op.drop_table('grupo')
    op.drop_index(op.f('ix_rodada_modalidade_id'), table_name='rodada')
    op.drop_table('rodada')
    op.drop_index(op.f('ix_inscricao_modalidade_id'), table_name='inscricao')
    op.drop_index(op.f('ix_inscricao_equipe_id'), table_name='inscricao')
    op.drop_table('inscricao')
    op.drop_index(op.f('ix_ficha_modalidade_id'), table_name='ficha')
    op.drop_table('ficha')
    op.drop_index(op.f('ix_modalidade_evento_id'), table_name='modalidade')
    op.drop_table('modalidade')
    op.drop_index(op.f('ix_audit_log_usuario_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entidade_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('evento')
    op.drop_table('equipe')
    # ### end Alembic commands ###

    # Tipos ENUM nativos do Postgres nao sao removidos automaticamente pelo
    # drop_table gerado acima; sem isso, um downgrade seguido de upgrade falha
    # com "type already exists".
    for enum_name in (
        "lancamento_status",
        "modificador_tipo",
        "criterio_tipo",
        "modo_horario",
        "rodada_status",
        "partida_status",
        "ficha_status",
        "modalidade_status",
        "consolidacao",
        "formato_chaveamento",
        "tipo_disputa",
        "evento_status",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
