"""equipe adiciona presente

Revision ID: e37fd78112f0
Revises: 6a506624890d
Create Date: 2026-10-05 18:14:22.012068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37fd78112f0'
down_revision: Union[str, None] = '6a506624890d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipe', sa.Column('presente', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipe', 'presente')
    # ### end Alembic commands ###
